### ISSUE TITLE
Неправильное отображение прогрузки видео

### ISSUE THREAD

**Issue by cjvth** [Ponywka/Multitrack.JS#10]
В Яндекс.Браузере если нажать в середину видео, индикатор прогрузки будет отображаться немного правее, чем должен быть. Видео при этом идёт с нужного момента.

![image](https://user-images.githubusercontent.com/40120650/82123010-37de0180-97c1-11ea-8663-4d58e6cf9f88.png)

В Торе, на движке как в Firefox, всё работает нормально

**Comment by Ponywka** [comment]
Всё работает отлично, это так работает движок Chromium
